- hosts: workers
  remote_user: "{{ ansible_user_workers }}"
  tasks:
  - name: Set DNS server to azure one
    ansible.builtin.shell: "networksetup -setdnsservers Ethernet {{ dns_servers }}; networksetup -setsearchdomains Ethernet prd.itsme.internal itsme.internal"
    become: true
  - name: Turn off power saving
    ansible.builtin.shell: "pmset -a sleep 0; pmset -a disablesleep 1; pmset -a standby 0; pmset -a autopoweroff 0"
    become: true
  - name: Turn on standby for mac between 1 am and 4 am - mac needs to be in standby for MAC OS updates
    ansible.builtin.shell: "pmset repeat sleep MTWRFSU 01:00:00 wake MTWRFSU 04:00:00"
    become: true
  - name: Turn on AutomaticDownload of updates
    ansible.builtin.shell: defaults write /Library/Preferences/com.apple.SoftwareUpdate AutomaticDownload -boolean true
    become: true
  - name: Turn on CriticalUpdateInstall of updates
    ansible.builtin.shell: defaults write /Library/Preferences/com.apple.SoftwareUpdate CriticalUpdateInstall -boolean true
    become: true
  - name: Turn on AutomaticCheckEnabled of updates
    ansible.builtin.shell: defaults write /Library/Preferences/com.apple.SoftwareUpdate AutomaticCheckEnabled -bool true
    become: true
  - name: Turn on AutomaticallyInstallMacOSUpdates of updates
    ansible.builtin.shell: defaults write /Library/Preferences/com.apple.SoftwareUpdate AutomaticallyInstallMacOSUpdates -bool true
    become: true


- name: Command Line Tools
  hosts: workers
  remote_user: "{{ ansible_user_workers }}"
  roles:
    - { role: elliotweiser.osx-command-line-tools }

- name: Install Homebrew
  hosts: workers
  remote_user: "{{ ansible_user_workers }}"
  roles:
    - geerlingguy.mac.homebrew

- hosts: workers
  remote_user: "{{ ansible_user_workers }}"
  tasks:
    - name: Update and upgrade Homebrew packages
      homebrew:
        update_homebrew: true
        upgrade_all: true

- name: Orchard Worker Service
  hosts: workers
  remote_user: "{{ ansible_user_workers }}"
  roles:
    - role: orchard-worker-service
